### ISSUE TITLE
Implementar novo tipo de dado datagrid

### ISSUE THREAD

**Issue by crebollobr** [digital-guard/preserv#115]
Para importar dados do tipo grid como 

https://geoportal.dane.gov.co/descargas/CNPV2018/Shapefile/ShapefileGrid1km2_VihopeCNPV2018.rar

Tipo do dado datagrid.

Exemplo: make_conf.yaml ( não funciona, somente para exemplo )
```
  datagrid:
        subtype: full
        method: shp2sql
        file: 1
        sql_select: ['gid', 'nomelog AS via_name', 'endereco_n AS house_number']
        orig_filename: rb_20201116/lotes
```
