### ISSUE TITLE
Incluir o tamanho em bytes dos arquivos em make_conf.yaml

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv#21]
O tamanho, por ser arquivo não-sigiloso,  **faz parte da caracterização do arquivo** e do critério de **garantia da integridade** &mdash; corromper uma chave criptográfica (MD5, SHA256 ou outra) é muito mais difícil quando o tamanho do arquivo é preservado. 

Exemplo: o arquivo [`410d02a`](http://dl.digital-guard.org/410d02a87e8d2955849ba644ed8830f3d6761b31f4d0dbf044d39975ffc02be1.zip) da Colômbia tem **4202017 bytes** (4,1M). No YAML de http://git.digital-guard.org/preserv-CO/blob/main/data/ANT/Medellin/_pk002/make_conf.yaml
passaremos a ter o atributo  *size*:

```yaml
files:
  -
    p:    1
    file: 410d02a87e8d2955849ba644ed8830f3d6761b31f4d0dbf044d39975ffc02be1.zip
    name: Malla Vial
    size: 4202017
```

Esse atributo não precisa ser gerado manualmente, pode ser inserido (e/ou conferido) por software... Idealmente um esqueleto do YAML já seria gerado por make aplicado aos dados da pasta (próxima issue ou expansão desta).
