### ISSUE TITLE
Eclusa gerando make_conf preliminar

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv#29]
Com os dados da planilha e do próprio filesystem (incluindo arquivo txt de `sha256sum`). Exemplo do que teria sido o pré-yaml de [preserv-BR/AC/RioBranco/_pk046/make_conf.yaml](https://github.com/digital-guard/preserv-BR/blob/main/data/AC/RioBranco/_pk046/make_conf.yaml):  

```yaml
pkid: 46
pkversion: 001
schemaId_input: ref027a 

files:
  -
    p:    1
    file: d96f47270e22336cf4660f742ae4dba5694f15c6833363167c91d9fc9929871b.zip
    name: Lotes
    size: 12086731
    
  -
    p:    2
    file: 73d02ba0ae4b0a994a629f7d06f0a027259f5c1d97e53f9b771fecd345c2a02b.zip
    name: Bairros
    size: 4527739

  -
    p:    3
    file: 29d68e5ce006079b06b710cc2df3aa08d6cb6934f32bc0b29fc46d3e8272ff77.rar
    name: Eixos
    size: 316372
```

----

@crebollobr, confirme que esse tipo de automação  ajuda no *workflow*, estimando o ganho médio em minutos, por YAML criado.
